spring.application.name=Femto Falconia project
spring.datasource.url=jdbc:postgresql://falconia.cp00sqsq6h89.ca-central-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=arpitgahlot
spring.jpa.hibernate.ddl-auto=update