spring.application.name=Femto Falconia project
spring.datasource.url=jdbc:postgresql://localhost:5432/falconia
spring.datasource.username=postgres
spring.datasource.password=asixabs
spring.jpa.hibernate.ddl-auto=update